### ISSUE TITLE
ENROOT_REMAP_ROOT,

### ISSUE THREAD

**Issue by staeglis** [ginkgo-project/gitlab-hpc-ci-cb#11]
Hi,

at the moment it's not possible to become root inside the container or make it writable I assume?

Best,
Stefan

**Comment by tcojean** [comment]
Hi, I believe that should already be done? Enroot supports `--rw` and we leverage that, see:
https://github.com/NVIDIA/enroot/blob/master/doc/cmd/start.md#usage
https://github.com/ginkgo-project/gitlab-hpc-ci-cb/blob/master/run.sh#L36

**Comment by staeglis** [comment]
You are right But there isn't any option to set ENROOT_REMAP_ROOT, is it? I could set this via enroot config file of course.

**Comment by tcojean** [comment]
Ah, this is what you mean. I believe adding `--root` or `-r` to the start command would take care of this. We can add an extra optional variable which if the user sets it, we add the `--root` option to the `enroot start` commands.
