### ISSUE TITLE
"Invalid image reference" when using private gitlab registry

### ISSUE THREAD

**Issue by staeglis** [ginkgo-project/gitlab-hpc-ci-cb#9]
Hi,

there seems to be an issue with the login to a private registry. It works with public images from docker hub.

Best,
Stefan

**Comment by tcojean** [comment]
Hi, thanks for the heads up. I can say I never tried this as our images are always public. I believe this might be related to how enroot and its credentials work, maybe this documentation helps: https://github.com/NVIDIA/enroot/blob/master/doc/cmd/import.md#description

I would be happy to help if you need to change something or have a hard time debugging the issue.

**Comment by tcojean** [comment]
By default we use `docker://` and the image scheme is quite simple (we assume dockerhub connection). Maybe we could add more configuration options to use either `dockerd://` or add tokens and other login details as needed.

**Comment by staeglis** [comment]
Should I be able to access all Gitlab CI variables there including and ${CI_REGISTRY_USER} and ${CI_REGISTRY_PASSWORD}?

I've tried it likethis:
```
    if [[ ${CUSTOM_ENV_CI_JOB_IMAGE} == "${CI_REGISTRY}"* ]]; then
      URL="docker://${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}@${CUSTOM_ENV_CI_JOB_IMAGE}"
    else
      URL="docker://${CUSTOM_ENV_CI_JOB_IMAGE}"
    fi
```

**Comment by tcojean** [comment]
Maybe what you are missing is the `CUSTOM_ENV_` prefix. All user-provided variables have a `CUSTOM_ENV_` prefix, see https://docs.gitlab.com/runner/executors/custom.html#stages

**Comment by staeglis** [comment]
Thanks now it fails with exit code 56:
```
    if [[ ${CUSTOM_ENV_CI_JOB_IMAGE} == "${CI_REGISTRY}"* ]]; then
        URL="docker://${CUSTOM_ENV_CI_REGISTRY_USER}:${CUSTOM_ENV_CI_REGISTRY_PASSWORD}@${CUSTOM_ENV_CI_REGISTRY}#${CUSTOM_ENV_CI_JOB_IMAGE#*$CUSTOM_ENV_CI_REGISTRY/}"
    else
        URL="docker://${CUSTOM_ENV_CI_JOB_IMAGE}"
    fi
```

**Comment by staeglis** [comment]
There was a bug in the proxy config

**Comment by tcojean** [comment]
Great news! Then it's now working as expected?

**Comment by staeglis** [comment]
Yes this issued is resolved by the merge request.
